# Set the Bluetooth and USB display name
CONFIG_ZMK_KEYBOARD_NAME="AK-34"

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable Rotary Encoder support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Force D3 (NFC pin) to act as a GPIO for the encoder yellow wire
CONFIG_NFCT_PINS_AS_GPIOS=y
