# Device Name
CONFIG_ZMK_KEYBOARD_NAME="AK-34"

# Studio Settings
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Encoder Settings
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Pin Fixes
CONFIG_NFCT_PINS_AS_GPIOS=y
